### ISSUE TITLE
Code Colors make Numbers Difficult to See

### ISSUE THREAD

**Issue by mhyee** [nuprl/website#224]
Moved from https://github.com/nuprl/nuprl.github.io/issues/82 (originally reported by @maxsnew)

> I was looking at an [an old blog post](http://prl.ccs.neu.edu/blog/2017/09/27/final-algebra-semantics-is-observational-equivalence/) and it numbers in the code look nearly invisible because they are white on a very light background, see the part right after "ghci will tell us".
> 
> I see this is defined in https://github.com/nuprl/nuprl.github.io/blob/master/css/pygments.css , does anyone that cares about design have an opinion on what color it should be? Just scrolling through css colors, [darkviolet](https://www.htmlcsscolor.com/hex/9400D3) is easy to read, but probably hard for colorblind people to distinguish from red.

Also reported on Twitter: https://twitter.com/bblfish/status/1175060862492729345

**Comment by bennn** [comment]
+1 for darkviolet

**Comment by ulysses4ever** [comment]
darkviolet looks legit. Let's do this.

**Comment by maxsnew** [comment]
Looks like @aatxe and @gasche are to blame: https://github.com/nuprl/website/pull/85 . Why did you guys change this?

**Comment by bennn** [comment]
I think the problem is that elements like `<mo>` appear in code & math. So the styles for code were accidentally getting applied to math because our `pygments.css` colors everything it can find in a document.

Everything should look okay if we:
1. add `.code` in front of every line in `pygments.css`, to keep it out of MathML elements
2. change the pygments colors to use `darkviolet` or `009999` or whatever looks good

If we want to change the math style in the future, let's add a new `.css` file for that.
