### ISSUE TITLE
publications: PLDI '22 update

### ISSUE THREAD

**Issue by ulysses4ever** [nuprl/website#309]
List of accepted papers is here: https://pldi22.sigplan.org/track/pldi-2022-pldi#event-overview

Brief look gives the following works from PRL:

* Computing Correctly with Inductive Relations / Zoe Paraskevopoulou, Aaron Eline, Leonidas Lampropoulos

* Deoptless: Speculation with Dispatched On-Stack Replacement and Specialized Continuations / Olivier Flückiger, Jan Ječmen, Sebastián Krynski, Jan Vitek

* Semantic Soundness for Language Interoperability / Daniel Patterson, Noble Mushtak, Andrew Wagner, Amal Ahmed

Maybe I missed something, so would be nice to double-check.

/cc @katherine-hough

**Comment by katherine-hough** [comment]
Thank you for the help. I planned to wait to add publications from PLDI to see if professors host the papers on their web pages. However, it probably makes more sense to just use the arxiv link for "Deoptless" and "Semantic Soundness for Language Interoperability", add them now, and then write myself a note to check the professors' pages later. I haven't found a link for "Computing Correctly with Inductive Relations" so I will check back on that later. I couldn't find a link for one of Frank's ICSE 2022 papers either so that is on the list as well. 

I have my calendar marked to check things again in early August since I expect everything from ICSE, ECOOP, ISSTA, PLDI, and maybe, ICFP to be posted by then.
