### ISSUE TITLE
When/how should we update Frog?

### ISSUE THREAD

**Issue by gasche** [nuprl/website#53]
https://github.com/greghendershott/frog/pull/180 was just merged upstream, which fixes a bug that affects our blog (it makes it painful to read for (at least) Thunderbird users that subscribed to the RSS feed.) How can I make sure that the version of `frog` used to generate the blog contains the fix?

**Comment by bennn** [comment]
You can check by:
- uninstalling `frog` on your machine (`raco pkg remove frog`)
- re-installing `frog` (`raco pkg install frog`)
- rebuilding the blog

If it looks good,* then it should look good on the website. Because building the website:
- uses a [travis](https://github.com/nuprl/website/blob/master/.travis.yml) script
- which [installs](https://github.com/nuprl/website/blob/master/install-racket.sh) Racket v6.6
- and then runs the website/blog's [Makefiles](https://github.com/nuprl/website/blob/master/blog/Makefile);
- the blog's Makefile runs `raco pkg install frog`
- which gets the "most recent available frog"

Racket's basically "rolling release" for all packages. You can make a version exception (users of Racket v6.6 get the v6.6 of package "My-Pkg"), but `frog` isn't doing that so the website should be getting the most up-to-date.

(* If it doesn't look good, maybe wait a few hours for the Racket package server to update its copy of frog)
