### ISSUE TITLE
Don't put the secure token in plaintext

### ISSUE THREAD

**Issue by bennn** [nuprl/website#57]
Read this page:
https://docs.travis-ci.com/user/environment-variables/

Then figure out how to change the `.travis.yml` (here and/or at prl.github.io) to not store the secure token in plaintext.

**Comment by gasche** [comment]
It may be the case that the variable currently in our `.travis.yml` is actually encrypted with the repo's secret key (see the [travis documentation on this](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml)), and thus nothing needs to be done.

**Comment by dbp** [comment]
Yes it's encrypted. I think I documented this somewhere. Let me try to find
it....

**Comment by bennn** [comment]
swerve

**Comment by dbp** [comment]
Ah yes, here is said documentation:

https://github.com/nuprl/website/blob/master/SETUP.md

Any account with write access to the repo would work, but for security it
shouldnt have other access (so the token currently there is a github
account with only access to that repo), since anyone with commit access to
the source repo controls the script Travis runs, so could change it to, for
example, send the token somewhere nefarious. If you used your personal
account, any lab member could get access to your private repository.
